# Generated by Django 6.1 on 2026-08-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tbs.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=50, unique=True)),
                ('problem', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('possible_causes', models.JSONField(blank=True, default=list)),
                ('diagnostic_questions', models.JSONField(blank=True, default=list)),
                ('commands', models.JSONField(blank=True, default=list)),
                ('troubleshooting_steps', models.JSONField(blank=True, default=list)),
                ('possible_solutions', models.JSONField(blank=True, default=list)),
                ('prevention', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('estimated_fix_time', models.CharField(blank=True, max_length=100)),
                ('related_problems', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='tbs.subcategory')),
            ],
            options={
                'ordering': ['problem_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_per_category'),
        ),
    ]
